apiVersion: zonalshiftmgr.keikoproj.io/v1
kind: AvailabilityZoneShift
metadata:
  labels:
    app.kubernetes.io/name: availabilityzoneshift
    app.kubernetes.io/instance: availabilityzoneshift-sample
    app.kubernetes.io/part-of: az-shift-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: az-shift-operator
  name: availabilityzoneshift-sample
spec:
  impairedAz: us-east-1a
